### ISSUE TITLE
LoadError: cannot load such file -- gb2260

### ISSUE THREAD

**Issue by csxiaodiao** [saberma/china_city#29]
```ruby
rake db:drop 
rake aborted!
LoadError: cannot load such file -- gb2260
/home/pc/.rvm/gems/ruby-2.2.2@leadings_development/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
/home/pc/.rvm/gems/ruby-2.2.2@leadings_development/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
/home/pc/.rvm/gems/ruby-2.2.2@leadings_development/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/pc/.rvm/gems/ruby-2.2.2@leadings_development/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
/home/pc/.rvm/gems/ruby-2.2.2@leadings_development/gems/china_city-0.0.5/lib/tasks/china_city_tasks.rake:1:in `<top (required)>'
/home/pc/.rvm/gems/ruby-2.2.2@leadings_development/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
/home/pc/.rvm/gems/ruby-2.2.2@leadings_development/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `block in load'
/home/pc/.rvm/gems/ruby-2.2.2@leadings_development/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/pc/.rvm/gems/ruby-2.2.2@leadings_development/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
/home/pc/.rvm/gems/ruby-2.2.2@leadings_development/gems/railties-4.2.5/lib/rails/engine.rb:658:in `block in run_tasks_blocks'
/home/pc/.rvm/gems/ruby-2.2.2@leadings_development/gems/railties-4.2.5/lib/rails/engine.rb:658:in `each'
/home/pc/.rvm/gems/ruby-2.2.2@leadings_development/gems/railties-4.2.5/lib/rails/engine.rb:658:in `run_tasks_blocks'
/home/pc/.rvm/gems/ruby-2.2.2@leadings_development/gems/railties-4.2.5/lib/rails/application.rb:451:in `block in run_tasks_blocks'
/home/pc/.rvm/gems/ruby-2.2.2@leadings_development/gems/railties-4.2.5/lib/rails/engine/railties.rb:13:in `each'
/home/pc/.rvm/gems/ruby-2.2.2@leadings_development/gems/railties-4.2.5/lib/rails/engine/railties.rb:13:in `each'
/home/pc/.rvm/gems/ruby-2.2.2@leadings_development/gems/railties-4.2.5/lib/rails/application.rb:451:in `run_tasks_blocks'
/home/pc/.rvm/gems/ruby-2.2.2@leadings_development/gems/railties-4.2.5/lib/rails/engine.rb:453:in `load_tasks'
/RAILS_PATH/Rakefile:6:in `<top (required)>'
(See full trace by running task with --trace)

```

**Comment by ken-wong** [comment]
我也遇到这个问题了。
0.04版本没有问题。

**Comment by wjp2013** [comment]
gem的依赖没有解决好，在作者修复这个问题之前，最简单的办法是 gemfile 这里这么改一下

```
# ChinaCity 省市区级联选择
gem 'GB2260'
gem 'china_city', '0.0.5'
```

**Comment by wjp2013** [comment]
参考这个
https://github.com/saberma/china_city/pull/28

**Comment by saberma** [comment]
已在 0.0.6 版本修正此问题，https://github.com/saberma/china_city/commit/598aa5c08b35d795e3a237dbfaa79d10e0dc4a79
